on:
  push:
    tags:
      - "v*"

name: Create Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    container: amazonlinux:latest
    steps:
      - name: Install pre-requisites
        run: |
          yum install make tar zip git -y
          yum install python3.12 -y
          python3.12 -m ensurepip --upgrade

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create lambda package
        run: |
          ./package.sh

      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: /__w/certbot-lambda/certbot-lambda/certbot/certbot-lambda.zip
